name: Forecast
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - oracle-ads>=2.9.0
      - prophet
      - neuralprophet
      - pmdarima
      - statsmodels
      - datapane
      - cerberus
      - sktime
      - shap
      - autots[additional]
      - optuna==3.1.0
      - oracle-automlx==23.4.1
      - oracle-automlx[forecasting]==23.4.1
